create end point login #15
GSG-G10/Housy pull request #33
Opened 2021-10-28 09:44 UTC by mohammedsalah7

2021-10-29 18:23 UTC, ElhamFadel submitted a review, later dismissed

2021-10-30 00:32 UTC, Mu7ammadAbed requested changes
I think you need to update your branch to the latest development version 
`git pull origin development`
and there's an env requiring in the `connection` file you have to keep it there

2021-10-30 00:32 UTC, Mu7ammadAbed commented on server/controllers/users/login.js
> +      throw new Error({ message: 'Invalid email or password' });
```suggestion
      return res.status(400).json({ message: 'Invalid email or password' });
```

2021-10-30 00:32 UTC, Mu7ammadAbed commented on server/controllers/users/login.js
> +      throw new Error({ message: 'Invalid email or password' });
```suggestion
      return res.status(400).json({ message: 'Invalid email or password' });
```

2021-10-30 00:32 UTC, Mu7ammadAbed commented on server/controllers/users/login.js
> +    const compared = await bcrypt.compare(password, rows[0].password);
You can make your controller a little bit organizer by splitting these
```suggestion
    }
    
    const compared = await bcrypt.compare(password, rows[0].password);
```

2021-10-30 00:32 UTC, Mu7ammadAbed commented on server/controllers/users/login.js
> +    return res.cookie('token', token).json({ message: 'You are Logged Successfully' });
Why would you send all these data in the token ?
you only need the id and the role if there's any
```suggestion
    const token = await signToken(email, rows[0].id);
    
    return res.cookie('token', token).json({ message: 'You are Logged Successfully' });
```

2021-10-30 23:04 UTC, Mu7ammadAbed commented
You need to update the branch with the development and resolve your conflicts, be aware that there are some changes with the routes file.

2021-10-31 10:13 UTC, Mu7ammadAbed submitted a review, later dismissed

2021-10-31 10:21 UTC, ElhamFadel approved these changes

2021-10-31 14:03 UTC, Mu7ammadAbed approved these changes

2021-10-31 14:13 UTC, muhammadharoun approved these changes

2021-10-31 14:18 UTC, ElhamFadel approved these changes

2021-10-31 14:19 UTC, merged