edit estate function and update query
GSG-G10/Housy pull request #34
Opened 2021-10-28 12:43 UTC by muhammadharoun

2021-10-29 18:23 UTC, ElhamFadel submitted a review, later dismissed

2021-10-30 00:37 UTC, Mu7ammadAbed requested changes
What is the case if there was no estate with this id?
What if the database throws an error for some reason and the row didn't update and you still sending status code 200(ok)?

2021-10-30 00:37 UTC, Mu7ammadAbed commented on server/controllers/estates/editEstate.js
> +    );
You need to fix this and make it more readable

2021-10-30 00:37 UTC, Mu7ammadAbed commented on server/controllers/estates/editEstate.js
> +    );
and by the way, you can destructure them from the result directly

2021-10-30 00:38 UTC, Mu7ammadAbed requested changes

2021-10-30 00:38 UTC, Mu7ammadAbed commented on server/test/index.test.js
> +// });
??

2021-10-30 23:19 UTC, Mu7ammadAbed requested changes
You need to convert your tests to `async/await` and you need to cover more cases in your tests

2021-10-30 23:19 UTC, Mu7ammadAbed commented on server/controllers/estates/editEstate.js
> +    const editResult = await editEstateQuery(
```suggestion
    const { rowCount } = await editEstateQuery(
```

2021-10-30 23:19 UTC, Mu7ammadAbed commented on server/controllers/estates/editEstate.js
>      res.json({ status: 200 });
```suggestion
    if (rowCount === 0) {
      return res.status(400).json({ status: 400, message: 'enter valid estate id ' });
    }

    res.json({ message: 'Estate updated successfully' });
```

2021-10-30 23:22 UTC, Mu7ammadAbed commented on server/controllers/users/userEstates.js
> +// eslint-disable-next-line consistent-return
```suggestion
```

2021-10-31 10:47 UTC, ElhamFadel approved these changes

2021-10-31 11:42 UTC, mohammedsalah7 submitted a review, later dismissed

2021-10-31 12:24 UTC, Mu7ammadAbed approved these changes

2021-10-31 13:01 UTC, mohammedsalah7 approved these changes

2021-10-31 13:12 UTC, merged