DELETE || ESTATE
GSG-G10/Housy pull request #35
Opened 2021-10-28 13:12 UTC by ElhamFadel

- success
<img width="529" alt="screenShoot" src="https://user-images.githubusercontent.com/65178119/139314770-0c1c992a-db43-4155-b728-fef463c41834.PNG">

- Faild 
<img width="536" alt="404" src="https://user-images.githubusercontent.com/65178119/139314836-a0515781-cbec-41bb-9df6-760f23efd3bd.PNG">

- test
<img width="563" alt="estate" src="https://user-images.githubusercontent.com/65178119/139314879-8890157f-8ff9-4392-bcdf-a760d37e7e8a.PNG">

2021-10-30 00:41 UTC, Mu7ammadAbed requested changes

2021-10-30 00:41 UTC, Mu7ammadAbed commented on server/controllers/estates/deleteEstate.js
> +  if (!Number.isInteger(estateId) || estateId <= 0) {
```suggestion
  if (!estateId > 0) {
```

2021-10-30 00:41 UTC, Mu7ammadAbed commented on server/controllers/estates/deleteEstate.js
> +    if (row.rowCount > 0) {
```suggestion
    const { rowCount } = await deleteEstate(estateId);
    if (rowCount > 0) {
```

2021-10-30 23:01 UTC, Mu7ammadAbed submitted a review, later dismissed

2021-10-30 23:02 UTC, Mu7ammadAbed commented
Resolve the conflicts and be aware while fixing the test file since some lines would consider them as mutual while they are different and need to be copied and pasted again.

2021-10-31 08:54 UTC, Mu7ammadAbed approved these changes

2021-10-31 08:58 UTC, Mu7ammadAbed approved these changes

2021-10-31 09:37 UTC, mohammedsalah7 approved these changes

2021-10-31 10:49 UTC, muhammadharoun approved these changes

2021-10-31 10:50 UTC, merged