PUT || Edit User
GSG-G10/Housy pull request #67
Opened 2021-10-31 11:12 UTC by ElhamFadel

2021-10-31 16:11 UTC, aaamra requested changes

2021-10-31 16:11 UTC, aaamra commented on server/routes/index.js
> +router.use('/users', users);
why you added this line ?

its already exists in line 6

2021-10-31 16:11 UTC, aaamra commented on server/controllers/users/putAgent.js
> +    const { error, value } = await editAgentSchema.validate({ ...req.body, userId });
use `validateAsync` instead of `validate`

2021-10-31 16:11 UTC, aaamra commented on server/test/index.test.js
> +describe('test Edit Agent data /users/:iduser  ', () => {
Great work at tests

but i suggest you to create multiple files for each group of related tests
its easier to read 

this file is about 300 lines

2021-10-31 16:25 UTC, emanNahed approved these changes

2021-11-02 13:31 UTC, Mu7ammadAbed commented on server/routes/index.js
> +router.post('/login', login);
This belongs to the user route

2021-11-03 14:24 UTC, Mu7ammadAbed approved these changes

2021-11-03 14:51 UTC, emanNahed approved these changes

2021-11-03 15:28 UTC, aaamra approved these changes

2021-11-03 15:28 UTC, merged