Development
GSG-G10/Housy pull request #72
Opened 2021-11-01 14:04 UTC by ElhamFadel

2021-11-03 17:59 UTC, NoureldeanSaed requested changes

2021-11-03 17:59 UTC, NoureldeanSaed commented on client/src/components/Footer/Footer.js
> +        <section className="section2">
Whenever you see code being repetitive, then you're doing something wrong.
All these sections and links could be generalized.
You could have an object like this:
```
[
            {
              title: 'About us',
              links: [
                {href: 'http://', name: 'Story', /** more props */}, 
                {href: 'http://', name: 'Clients', /** more props */}, 
                ...
              ]
            }
          ]
```
And spread your properties accordingly.
Advantage of using this style, is you can toggle on/off any more properties you wish to add.

2021-11-03 17:59 UTC, NoureldeanSaed commented on client/src/components/Footer/footer.css
> +.section2 {
Rename your classes to something more readable. And generalize properties like display and alignment to separate classes, since you use those a lot.

2021-11-03 17:59 UTC, NoureldeanSaed commented on server/controllers/users/putAgent.js
> +    return res.status(404).json({
Not an 404.

2021-11-05 10:52 UTC, Mu7ammadAbed commented on server/controllers/users/putAgent.js
> +    const { id: userId } = req.user;
```suggestion
    const { userId } = req.user;
```

2021-11-05 12:28 UTC, merged