create navbar component with style #40
GSG-G10/Housy pull request #74
Opened 2021-11-01 15:00 UTC by mohammedsalah7

![Screenshot from 2021-11-01 16-57-16](https://user-images.githubusercontent.com/28189827/139692713-1a883132-c708-4b1c-878c-f4e8298deed6.png)

2021-11-03 08:17 UTC, Mu7ammadAbed commented on client/src/components/Navbar/index.js
> +  const [state, setstate] = useState(true);
```suggestion
  const [logged, setLogged] = useState(true);
```

2021-11-05 11:27 UTC, Mu7ammadAbed requested changes

2021-11-05 11:27 UTC, Mu7ammadAbed commented on client/src/components/Navbar/index.js
> +import Link from '@mui/material/Link';
There's no need to use the the `react-router-dom' Link inside of `material-ui` Link
```suggestion
import { Link } from 'react-router-dom';
```

2021-11-05 11:27 UTC, Mu7ammadAbed commented on client/src/components/Navbar/index.js
> +        <Link component={RouterLink} to="/">
```suggestion
        <Link to="/">
```

2021-11-05 11:27 UTC, Mu7ammadAbed commented on client/src/components/Navbar/index.js
> +          <Link component={RouterLink} to="/" style={{ color: '#797B7D', textDecoration: 'none' }}>
```suggestion
          <Link to="/" style={{ color: '#797B7D', textDecoration: 'none' }}>
```

2021-11-05 11:27 UTC, Mu7ammadAbed commented on client/src/components/Navbar/index.js
> +          <Link component={RouterLink} to="/signup" style={{ color: '#797B7D', textDecoration: 'none' }}>
```suggestion
          <Link to="/signup" style={{ color: '#797B7D', textDecoration: 'none' }}>
```

2021-11-05 11:27 UTC, Mu7ammadAbed commented on client/src/components/Navbar/index.js
> +          <Link component={RouterLink} to="/" style={{ color: '#797B7D', textDecoration: 'none' }}>
```suggestion
          <Link to="/" style={{ color: '#797B7D', textDecoration: 'none' }}>
```

2021-11-05 11:27 UTC, Mu7ammadAbed commented on client/src/components/Navbar/index.js
> +          <Link component={RouterLink} to="/" style={{ color: '#797B7D', textDecoration: 'none' }}>
```suggestion
          <Link to="/" style={{ color: '#797B7D', textDecoration: 'none' }}>
```

2021-11-05 11:27 UTC, Mu7ammadAbed commented on client/src/components/Navbar/index.js
> +        {/* </Stack> */}
??
```suggestion
```

2021-11-05 11:27 UTC, Mu7ammadAbed commented on client/src/components/Navbar/index.js
> +            <Link component={RouterLink} to="/login" className="btn-host">
```suggestion
            <Link to="/login" className="btn-host">
```

2021-11-05 11:27 UTC, Mu7ammadAbed commented on client/src/components/Navbar/index.js
> +            <Link component={RouterLink} to="/">
```suggestion
            <Link to="/">
```

2021-11-07 10:42 UTC, Mu7ammadAbed submitted a review, later dismissed

2021-11-07 10:59 UTC, Mu7ammadAbed approved these changes

2021-11-07 11:27 UTC, muhammadharoun approved these changes

2021-11-07 11:31 UTC, merged