54 home images section
GSG-G10/Housy pull request #78
Opened 2021-11-02 14:44 UTC by muhammadharoun

![Screenshot from 2021-11-02 16-43-39](https://user-images.githubusercontent.com/61364683/139869725-864e3e89-a79a-46dd-919b-89754befcf24.png)

2021-11-04 08:31 UTC, mohammedsalah7 requested changes
1- You should start the name of the component capital letter  
2- add margin-bottom to right  images

2021-11-04 08:33 UTC, mohammedsalah7 reviewed
You should in folder set name index.js to file component, not like this
  client/src/components/ImageSection/ImageSection.js 
  like this :
/components/ImageSection/index.js

2021-11-04 19:32 UTC, mohammedsalah7 approved these changes

2021-11-07 10:25 UTC, Mu7ammadAbed approved these changes

2021-11-07 10:25 UTC, merged